= Proteus Mawar

== Summary

Proteus Mawar adalah _microservice_ yang menangani _request_ untuk transaksi dari channel Telegram dan SMS, nantinya setiap transaksi akan diteruskan ke GM (Proteus ini merupakan Proteus In versi khusus untuk Alphapay saja).

Dikarenakan Proteus Mawar ini menggunakan _Event-driven Architecture_ yang sangat berbeda dengan _API-driven Architecture,_ maka di microservice ini tidak ada API doc-nya, karena tidak ada endpoint yang spesifik yang bisa dihit.
Bisa dikatakan, Proteus Mawar ini formatnya sudah ditentukan dari awal dalam suatu _event._

(Contoh format dapat dilihat di Page Format Request di bawah)

== Anggota Tim Proteus Mawar

|===
| Posisi | Nama | Tim

| Product Owner
| Leo Himawan Adiakso
| Putterfish

| Development Manager
| Evan Sujanto
| Putterfish

| Lead Software Engineer
| Kevin Setiawan Tanzil
| Putterfish

| Lead Quality Engineer
| Fransiska Maya
| Pangolin

| Lead System Analyst
| Fiqri Aulia Rahman
| Strix
|===


== Technical Information

<<proteus-mawar/url-proteus-mawar.adoc#, System URL Proteus Mawar>>

<<proteus-mawar/architecture-proteus-mawar.adoc#, Architecture Proteus Mawar>>

<<proteus-mawar/technology-proteus-mawar.adoc#, Technology Proteus Mawar>>

<<proteus-mawar/environment-proteus-mawar.adoc#, Environment Proteus Mawar>>

<<proteus-mawar/release-deploy-proteus-mawar.adoc#, Release and Deployment Proteus Mawar>>


== Onboarding Information

https://github.com/sepulsa/proteus-mawar

== Dokumentasi

<<proteus-mawar/unit-request-proteus-mawar.adoc#, Unit Request Proteus Mawar>>
